server:
  port: 80
  sessionTimeout: 30
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: root
    sql-script-encoding: utf-8
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000  
    validationQuery: SELECT 1 FROM DUAL  
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true  
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  http:
    encoding.charset: UTF-8  
    encoding.enable: true  
    encoding.force: true 
  jpa: 
    showsql: true
mybatis:
  type-aliases-package: com.turing.manage.entity
  #config-locations: classpath:mapper/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  
banner:
  charset: UTF-8
  location: classpath:banner.txt

logging:
  config: classpath:logback.xml
  
jedis:
  database: 0
  host: 127.0.0.1
  port: 6379
  password: turingzhaogang_20160725
  timeout: 1000
  pool:
    maxTotal: 600
    maxWaitMillis: 1000
    maxIdle: 300
    minIdle: 0
    testOnBorrow: true
#redis初始化列表
redis:
  cacheList:
    - student
    - country